services:
  user-service:
    env_file:
      - ./nacos/env/user-service.test.env

  destination-service:
    env_file:
      - ./nacos/env/destination-service.test.env

  itinerary-service:
    env_file:
      - ./nacos/env/itinerary-service.test.env

  gateway-service:
    env_file:
      - ./nacos/env/gateway-service.test.env
